version: '3.3'

services:
    mysql:
        container_name: assessment_db
        hostname: assessment_db
        image: mysql:8.0.26
        cap_add:
            - SYS_NICE
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: nclose_assessment
            MYSQL_USER: nclose
            MYSQL_PASSWORD: thisisnotagoodpassword
            MYSQL_ROOT_PASSWORD: thisisnotagoodpassword
        ports:
            - '3307:3306'
        stdin_open: true
        tty: true
        volumes:
            - ./mysql_data:/var/lib/mysql
        
        command: --default-authentication-plugin=mysql_native_password
